In [6]:
import eikon as ek
from datetime import datetime, timedelta
from dateutil.relativedelta import *
import os
ek.set_app_key('04851d8cdc3d47f7882782edf7d9abbf5999a94a')

file = open('asx200.csv')

stonks = []
for i in file:
    stonks.append(i.rstrip()+'.AX')
print('Complete')

Complete

In [45]:
try:
    os.mkdir('Tickerdata')
except FileExistsError:
    pass

start = "2019-06-01"
end = "2020-08-10"

#RUN WITH PRN.AX -AUSDRILL
#AOG.AX^L19
#BAL.AX^L19
#ALD.AX - CTX.AX (FORMER)
#VUK.AX - CYB.AX (FORMER)
#DLX.AX^H19
#HSO.AX^F19
#MYO.AX^E19
#NVT.AX^G19
#TME.AX^E19 /TMZ.NZ^E19 - REMOVE
#TPM.AX^G20
#WPR.AX - VVR.AX (FORMER)
for ticker in stonks[0:1]:
    print(ticker)
    req = ek.get_timeseries(["TME.AX^E19"], start_date = start,
    end_date = end, interval="daily")
    req.to_csv("Tickerdata/"+"TME"+".csv")

ABP.AX

2020-09-21 02:28:23,535 P[2636] [MainThread 15792] Error with TME.AX^E19: No data available for the requested date range
2020-09-21 02:28:23,536 P[2636] [MainThread 15792] TME.AX^E19: No data available for the requested date range |

EikonError: Error code -1 | TME.AX^E19: No data available for the requested date range |

ABP.AX      HIGH  CLOSE    LOW  OPEN   COUNT     VOLUME
Date
2019-06-03  3.91   3.88  3.830  3.83  1906.0   502488.0
2019-06-04  4.09   4.00  3.890  3.89  4328.0  2920684.0
2019-06-05  4.04   3.99  3.990  4.02  2206.0  1636836.0
2019-06-06  4.16   4.12  4.030  4.03  2725.0  1270087.0
2019-06-07  4.21   4.21  4.135  4.17  2581.0   656983.0
...          ...    ...    ...   ...     ...        ...
2020-08-04  2.71   2.69  2.650  2.70  1189.0   918478.0
2020-08-05  2.71   2.62  2.610  2.63  1203.0  1081901.0
2020-08-06  2.66   2.62  2.610  2.63   797.0   597599.0
2020-08-07  2.67   2.61  2.600  2.62  1081.0   728990.0
2020-08-10  2.68   2.67  2.620  2.64   703.0   517887.0

[302 rows x 6 columns]